// Mocks generated by Mockito 5.4.6 from annotations
// in pos/test/services/hardware/hardware_simulation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_pos_printer_platform/flutter_pos_printer_platform.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBluetoothPrinterConnector_0 extends _i1.SmartFake
    implements _i2.BluetoothPrinterConnector {
  _FakeBluetoothPrinterConnector_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTcpPrinterConnector_1 extends _i1.SmartFake
    implements _i2.TcpPrinterConnector {
  _FakeTcpPrinterConnector_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsbPrinterConnector_2 extends _i1.SmartFake
    implements _i2.UsbPrinterConnector {
  _FakeUsbPrinterConnector_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PrinterManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrinterManager extends _i1.Mock implements _i2.PrinterManager {
  MockPrinterManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BluetoothPrinterConnector get bluetoothPrinterConnector =>
      (super.noSuchMethod(
        Invocation.getter(#bluetoothPrinterConnector),
        returnValue: _FakeBluetoothPrinterConnector_0(
          this,
          Invocation.getter(#bluetoothPrinterConnector),
        ),
      ) as _i2.BluetoothPrinterConnector);

  @override
  _i2.TcpPrinterConnector get tcpPrinterConnector => (super.noSuchMethod(
        Invocation.getter(#tcpPrinterConnector),
        returnValue: _FakeTcpPrinterConnector_1(
          this,
          Invocation.getter(#tcpPrinterConnector),
        ),
      ) as _i2.TcpPrinterConnector);

  @override
  _i2.UsbPrinterConnector get usbPrinterConnector => (super.noSuchMethod(
        Invocation.getter(#usbPrinterConnector),
        returnValue: _FakeUsbPrinterConnector_2(
          this,
          Invocation.getter(#usbPrinterConnector),
        ),
      ) as _i2.UsbPrinterConnector);

  @override
  _i3.Stream<_i2.BTStatus> get stateBluetooth => (super.noSuchMethod(
        Invocation.getter(#stateBluetooth),
        returnValue: _i3.Stream<_i2.BTStatus>.empty(),
      ) as _i3.Stream<_i2.BTStatus>);

  @override
  _i3.Stream<_i2.USBStatus> get stateUSB => (super.noSuchMethod(
        Invocation.getter(#stateUSB),
        returnValue: _i3.Stream<_i2.USBStatus>.empty(),
      ) as _i3.Stream<_i2.USBStatus>);

  @override
  _i2.BTStatus get currentStatusBT => (super.noSuchMethod(
        Invocation.getter(#currentStatusBT),
        returnValue: _i2.BTStatus.none,
      ) as _i2.BTStatus);

  @override
  _i2.USBStatus get currentStatusUSB => (super.noSuchMethod(
        Invocation.getter(#currentStatusUSB),
        returnValue: _i2.USBStatus.none,
      ) as _i2.USBStatus);

  @override
  _i3.Stream<_i2.PrinterDevice> discovery({
    required _i2.PrinterType? type,
    bool? isBle = false,
    _i2.TcpPrinterInput? model,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #discovery,
          [],
          {
            #type: type,
            #isBle: isBle,
            #model: model,
          },
        ),
        returnValue: _i3.Stream<_i2.PrinterDevice>.empty(),
      ) as _i3.Stream<_i2.PrinterDevice>);

  @override
  _i3.Future<bool> connect({
    required _i2.PrinterType? type,
    required _i2.BasePrinterInput? model,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [],
          {
            #type: type,
            #model: model,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> disconnect({
    required _i2.PrinterType? type,
    int? delayMs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
          {
            #type: type,
            #delayMs: delayMs,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> send({
    required _i2.PrinterType? type,
    required List<int>? bytes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [],
          {
            #type: type,
            #bytes: bytes,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
