// Mocks generated by Mockito 5.4.6 from annotations
// in pos/test/presentation/blocs/cart/cart_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter/services.dart' as _i7;
import 'package:flutter_pos_printer_platform/flutter_pos_printer_platform.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pos/services/cash_session_service.dart' as _i9;
import 'package:pos/services/dto/create_sale_dto.dart' as _i4;
import 'package:pos/services/hardware/hardware_service.dart' as _i5;
import 'package:pos/services/hardware/receipt_generator.dart' as _i8;
import 'package:pos/services/sales_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSaleResult_0 extends _i1.SmartFake implements _i2.SaleResult {
  _FakeSaleResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SalesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSalesService extends _i1.Mock implements _i2.SalesService {
  MockSalesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i2.SaleResult> createSale(
    _i4.CreateSaleDto? dto,
    String? tenantId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSale,
          [
            dto,
            tenantId,
          ],
        ),
        returnValue: _i3.Future<_i2.SaleResult>.value(_FakeSaleResult_0(
          this,
          Invocation.method(
            #createSale,
            [
              dto,
              tenantId,
            ],
          ),
        )),
      ) as _i3.Future<_i2.SaleResult>);

  @override
  _i3.Future<void> cancelSale(
    String? saleId,
    String? userId,
    String? reason,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelSale,
          [
            saleId,
            userId,
            reason,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [HardwareService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHardwareService extends _i1.Mock implements _i5.HardwareService {
  MockHardwareService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<String> get onBarcodeScanned => (super.noSuchMethod(
        Invocation.getter(#onBarcodeScanned),
        returnValue: _i3.Stream<String>.empty(),
      ) as _i3.Stream<String>);

  @override
  _i3.Stream<_i6.PrinterDevice> scanPrinters(
          {_i6.PrinterType? type = _i6.PrinterType.network}) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanPrinters,
          [],
          {#type: type},
        ),
        returnValue: _i3.Stream<_i6.PrinterDevice>.empty(),
      ) as _i3.Stream<_i6.PrinterDevice>);

  @override
  _i3.Future<void> connect(
    _i6.PrinterDevice? device,
    _i6.PrinterType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #connect,
          [
            device,
            type,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> printReceipt(List<int>? bytes) => (super.noSuchMethod(
        Invocation.method(
          #printReceipt,
          [bytes],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> openDrawer() => (super.noSuchMethod(
        Invocation.method(
          #openDrawer,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void handleKeyEvent(_i7.KeyEvent? event) => super.noSuchMethod(
        Invocation.method(
          #handleKeyEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ReceiptGenerator].
///
/// See the documentation for Mockito's code generation for more information.
class MockReceiptGenerator extends _i1.Mock implements _i8.ReceiptGenerator {
  MockReceiptGenerator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<int>> generateReceiptFromResult({
    required _i2.SaleResult? saleResult,
    required List<_i4.PaymentDto>? payments,
    required String? tenantName,
    required String? branchName,
    required String? cashierName,
    required double? change,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateReceiptFromResult,
          [],
          {
            #saleResult: saleResult,
            #payments: payments,
            #tenantName: tenantName,
            #branchName: branchName,
            #cashierName: cashierName,
            #change: change,
          },
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<List<int>> generateReceipt(
    _i4.CreateSaleDto? sale,
    String? tenantName,
    String? branchName,
    String? cashierName,
    String? saleId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateReceipt,
          [
            sale,
            tenantName,
            branchName,
            cashierName,
            saleId,
            date,
          ],
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);

  @override
  _i3.Future<List<int>> generateSessionReport({
    required _i9.CashSessionSummary? summary,
    required String? tenantName,
    required String? branchName,
    required String? cashierName,
    required double? declaredAmount,
    required double? difference,
    String? justification,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateSessionReport,
          [],
          {
            #summary: summary,
            #tenantName: tenantName,
            #branchName: branchName,
            #cashierName: cashierName,
            #declaredAmount: declaredAmount,
            #difference: difference,
            #justification: justification,
          },
        ),
        returnValue: _i3.Future<List<int>>.value(<int>[]),
      ) as _i3.Future<List<int>>);
}
