/**
 * Error Code Enum
 * Standard error codes for API responses.
 */

/**
 * Authentication error codes
 */
export enum AuthErrorCode {
    INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
    TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
    TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
    TOKEN_MISSING = 'AUTH_TOKEN_MISSING',
    REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
    USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
    USER_BLOCKED = 'AUTH_USER_BLOCKED',
    USER_INACTIVE = 'AUTH_USER_INACTIVE',
    PASSWORD_MISMATCH = 'AUTH_PASSWORD_MISMATCH',
    TWO_FACTOR_REQUIRED = 'AUTH_2FA_REQUIRED',
    TWO_FACTOR_INVALID = 'AUTH_2FA_INVALID',
    SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
    INSUFFICIENT_PERMISSIONS = 'AUTH_INSUFFICIENT_PERMISSIONS',
}

/**
 * Validation error codes
 */
export enum ValidationErrorCode {
    REQUIRED_FIELD = 'VALIDATION_REQUIRED_FIELD',
    INVALID_FORMAT = 'VALIDATION_INVALID_FORMAT',
    INVALID_EMAIL = 'VALIDATION_INVALID_EMAIL',
    INVALID_PHONE = 'VALIDATION_INVALID_PHONE',
    INVALID_UUID = 'VALIDATION_INVALID_UUID',
    INVALID_DATE = 'VALIDATION_INVALID_DATE',
    INVALID_NUMBER = 'VALIDATION_INVALID_NUMBER',
    MIN_LENGTH = 'VALIDATION_MIN_LENGTH',
    MAX_LENGTH = 'VALIDATION_MAX_LENGTH',
    MIN_VALUE = 'VALIDATION_MIN_VALUE',
    MAX_VALUE = 'VALIDATION_MAX_VALUE',
    PATTERN_MISMATCH = 'VALIDATION_PATTERN_MISMATCH',
    UNIQUE_CONSTRAINT = 'VALIDATION_UNIQUE_CONSTRAINT',
}

/**
 * Resource error codes
 */
export enum ResourceErrorCode {
    NOT_FOUND = 'RESOURCE_NOT_FOUND',
    ALREADY_EXISTS = 'RESOURCE_ALREADY_EXISTS',
    CONFLICT = 'RESOURCE_CONFLICT',
    DELETED = 'RESOURCE_DELETED',
    ARCHIVED = 'RESOURCE_ARCHIVED',
}

/**
 * Business logic error codes
 */
export enum BusinessErrorCode {
    INSUFFICIENT_STOCK = 'BUSINESS_INSUFFICIENT_STOCK',
    CASH_SESSION_NOT_OPEN = 'BUSINESS_CASH_SESSION_NOT_OPEN',
    CASH_SESSION_ALREADY_OPEN = 'BUSINESS_CASH_SESSION_ALREADY_OPEN',
    SALE_ALREADY_COMPLETED = 'BUSINESS_SALE_ALREADY_COMPLETED',
    SALE_ALREADY_ANNULLED = 'BUSINESS_SALE_ALREADY_ANNULLED',
    PRODUCT_INACTIVE = 'BUSINESS_PRODUCT_INACTIVE',
    PRICE_LIST_NOT_FOUND = 'BUSINESS_PRICE_LIST_NOT_FOUND',
    LOT_EXPIRED = 'BUSINESS_LOT_EXPIRED',
    CREDIT_LIMIT_EXCEEDED = 'BUSINESS_CREDIT_LIMIT_EXCEEDED',
    PAYMENT_INSUFFICIENT = 'BUSINESS_PAYMENT_INSUFFICIENT',
    INVALID_OPERATION = 'BUSINESS_INVALID_OPERATION',
}

/**
 * Tenant error codes
 */
export enum TenantErrorCode {
    NOT_FOUND = 'TENANT_NOT_FOUND',
    INACTIVE = 'TENANT_INACTIVE',
    SUSPENDED = 'TENANT_SUSPENDED',
    TRIAL_EXPIRED = 'TENANT_TRIAL_EXPIRED',
    SUBSCRIPTION_EXPIRED = 'TENANT_SUBSCRIPTION_EXPIRED',
    LIMIT_EXCEEDED = 'TENANT_LIMIT_EXCEEDED',
    MAX_USERS_REACHED = 'TENANT_MAX_USERS_REACHED',
    MAX_BRANCHES_REACHED = 'TENANT_MAX_BRANCHES_REACHED',
}

/**
 * System error codes
 */
export enum SystemErrorCode {
    INTERNAL_ERROR = 'SYSTEM_INTERNAL_ERROR',
    DATABASE_ERROR = 'SYSTEM_DATABASE_ERROR',
    EXTERNAL_SERVICE_ERROR = 'SYSTEM_EXTERNAL_SERVICE_ERROR',
    RATE_LIMIT_EXCEEDED = 'SYSTEM_RATE_LIMIT_EXCEEDED',
    MAINTENANCE_MODE = 'SYSTEM_MAINTENANCE_MODE',
    SERVICE_UNAVAILABLE = 'SYSTEM_SERVICE_UNAVAILABLE',
}

/**
 * Combined error code type
 */
export type ErrorCode =
    | AuthErrorCode
    | ValidationErrorCode
    | ResourceErrorCode
    | BusinessErrorCode
    | TenantErrorCode
    | SystemErrorCode;
