import {
    Entity,
    Column,
    Index,
    ManyToOne,
    JoinColumn,
    PrimaryGeneratedColumn,
    CreateDateColumn,
    UpdateDateColumn,
    Unique,
} from 'typeorm';
import { IsString, IsBoolean, IsOptional, MaxLength } from 'class-validator';
import { AccountingPeriod } from './accounting-period.entity';

/**
 * AccountingEntry - Accounting journal entries
 * 
 * Can be auto-generated or manual.
 * 
 * @table accounting_entries
 */
@Entity('accounting_entries')
@Unique(['entryNumber'])
@Index(['tenantId', 'entryDate'])
@Index(['tenantId', 'periodId'])
@Index(['tenantId', 'referenceType', 'referenceId'])
export class AccountingEntry {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Column({ name: 'tenant_id', type: 'uuid' })
    @Index()
    tenantId: string;

    /** Entry number (unique) */
    @Column({ name: 'entry_number', type: 'varchar', length: 50 })
    @IsString()
    @MaxLength(50)
    entryNumber: string;

    /** Entry date */
    @Column({ name: 'entry_date', type: 'date' })
    entryDate: Date;

    /** Period ID */
    @Column({ name: 'period_id', type: 'uuid' })
    periodId: string;

    @ManyToOne(() => AccountingPeriod)
    @JoinColumn({ name: 'period_id' })
    period: AccountingPeriod;

    /** Reference type (polymorphic): sale, purchase, payment, etc. */
    @Column({ name: 'reference_type', type: 'varchar', length: 50, nullable: true })
    @IsOptional()
    @IsString()
    referenceType?: string;

    /** Reference ID */
    @Column({ name: 'reference_id', type: 'uuid', nullable: true })
    @IsOptional()
    referenceId?: string;

    /** Description */
    @Column({ type: 'text' })
    @IsString()
    description: string;

    /** Auto-generated flag */
    @Column({ name: 'is_auto_generated', type: 'boolean', default: false })
    @IsBoolean()
    isAutoGenerated: boolean;

    /** Status: draft, posted */
    @Column({ type: 'varchar', length: 20, default: 'draft' })
    @IsString()
    status: string;

    /** Created by user ID */
    @Column({ name: 'created_by', type: 'uuid', nullable: true })
    @IsOptional()
    createdBy?: string;

    @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
    createdAt: Date;

    @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
    updatedAt: Date;
}
