// Mocks generated by Mockito 5.4.6 from annotations
// in pos/test/presentation/blocs/auth/auth_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:event_bus/event_bus.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:pos/services/auth_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStreamController_0<T> extends _i1.SmartFake
    implements _i2.StreamController<T> {
  _FakeStreamController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  @override
  _i2.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i2.Future<bool>.value(false),
        returnValueForMissingStub: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<String> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i2.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i2.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i2.Future<String>);

  @override
  _i2.Future<void> forgotPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<Map<String, String?>> getContext() => (super.noSuchMethod(
        Invocation.method(
          #getContext,
          [],
        ),
        returnValue:
            _i2.Future<Map<String, String?>>.value(<String, String?>{}),
        returnValueForMissingStub:
            _i2.Future<Map<String, String?>>.value(<String, String?>{}),
      ) as _i2.Future<Map<String, String?>>);
}

/// A class which mocks [EventBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventBus extends _i1.Mock implements _i5.EventBus {
  @override
  _i2.StreamController<dynamic> get streamController => (super.noSuchMethod(
        Invocation.getter(#streamController),
        returnValue: _FakeStreamController_0<dynamic>(
          this,
          Invocation.getter(#streamController),
        ),
        returnValueForMissingStub: _FakeStreamController_0<dynamic>(
          this,
          Invocation.getter(#streamController),
        ),
      ) as _i2.StreamController<dynamic>);

  @override
  _i2.Stream<T> on<T>() => (super.noSuchMethod(
        Invocation.method(
          #on,
          [],
        ),
        returnValue: _i2.Stream<T>.empty(),
        returnValueForMissingStub: _i2.Stream<T>.empty(),
      ) as _i2.Stream<T>);

  @override
  void fire(dynamic event) => super.noSuchMethod(
        Invocation.method(
          #fire,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void destroy() => super.noSuchMethod(
        Invocation.method(
          #destroy,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
